apiVersion: "kubeflow.org/v1beta2"
kind: "TFJob"
metadata:
  name: "s3-gateway-copy"
  namespace: kubeflow 
spec:
  cleanPodPolicy: None 
  tfReplicaSpecs:
    Worker:
      replicas: 1 
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: papposilenus/tf_job_s3_gateway:8
              env:
                - name: S3_ENDPOINT
                  value: "10.28.13.156:600"
                - name: S3_USE_HTTPS
                  value: "0"
                - name: S3_VERIFY_SSL
                  value: "0"
              command:
                - "python"
                - "/var/tf_mnist/tf_job_s3_gateway.py"
                - "-b"
                - "master.testrepo"
                - "-i"
                - "/testdata"






